project_id = "sjrmpojssvfgquroywys"

[functions.dispatcher-multi]
verify_jwt = false

[functions.chatwoot-text-commands]
verify_jwt = false

[functions.api-key-auth]
verify_jwt = false

[functions.cards-api]
verify_jwt = false

[functions.ai-lead-score]
verify_jwt = false

[functions.dispatcher-automations]
verify_jwt = false
